[build]
  publish = "."
  command = "npm install --prefix netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
