[build]
  publish = "."
  command = "npm install --prefix netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
